version: "3.8"
services:
  model_1:
    build: ./model_service
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8001:8000"

  model_2:
    build: ./model_service
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8002:8000"

  model_3:
    build: ./model_service
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8003:8000"

  model_4:
    build: ./model_service
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8004:8000"

  model_5:
    build: ./model_service
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8005:8000"

  model_6:
    build: ./model_service
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8006:8000"

  model_7:
    build: ./model_service
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8007:8000"

  model_8:
    build: ./model_service
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8008:8000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - model_1
      - model_2
      - model_3
      - model_4
      - model_5
      - model_6
      - model_7
      - model_8
